### ISSUE TITLE
Button Group

### ISSUE THREAD

**Issue by tarikkirsanli** [kaancetin-f/ar-design#3]

**Comment by kaancetin-f** [comment]
@koadna Tam üzerinde çalışıyordum :) Çok güzel bir noktaya değindin :)

**Comment by kaancetin-f** [comment]
Çok güzel bir noktaya değindin :)

**Comment by kaancetin-f** [comment]
@koadna Bunun için bir geliştirme yaptım detaylı bir çalışma oldu. https://ardesign-dev.netlify.app/components/button buradan görebilirsin :)
